---
title: "Untitled"
format: html
---

# Participants

1. Mtwara DC
    - Fisheries officer (Habiba)
    - Das representative

2. MBREMP

    - Redfred ngowo
    - Davis Ulio
    - Mustafa
    - Musa
    - 

3. Technical
    - TNC (Senkondo, Emma and Glory)
    - WCS (Pagu)
    - Nelson Mandela (Semba)

4. Community

participants from outside the MBREMM were from the following villages:

    - Mgao
    - Msangamkuu

participants from inside the MBREMM were from the following village: 

    - Rivula
    - Msimbati
    - Mngoji
    - Mnazi
    - Nalingu

The meeting begin with 

- Emmanuel Mpina that explains the Bahari Yetu project, 
- Redfred Ngowo, talked about conservations and how relevant is with blue economy, ngow invited Das
- DAS talked about relevant of the marine assets (mangrove, coral reefs and seagrass) for income generating and how community can take that advantage. He further demonstrated with a cas of Zanzibar and how tourism is a key income gnerationg for individual and national

- Group photo
- Presentations
    - Mussa on ecological
    - Pagu the importance of ecology in the marine
    - Semba showcase the marine assets in Tanzania with focus in Mtwara
    - Senkondo presents on the objective of the Bahari Yetu and the key activities of the mission. He emphasise on the name of the project (Bahari Yetu) and how the community has a role in the conservation and restoration of the coral reef

    - Inventory of the ecosystem
    - Evaluation of the ecosystem
    - Restoration of coral reefs
            - In the damaged areas, we must assess the state of coral reefs in the selected areas
            - 


# Group session

Kilindi reef has been damaged ()


